###

GET http://localhost:3000/posts/6777832d405edb6f85461559

###

GET http://localhost:3000/posts?owner=POP


###
  
POST  http://localhost:3000/posts
Content-Type: application/json

{
"title": "Hello World",
"content": "This is my first post!",
"owner": "POP"
} 

###
  
PUT  http://localhost:3000/posts/6753ef9849a93e2b5d99241a
Content-Type: application/json

{
"title": "Updated File",
"content": "This is my second post!",
"owner": "ELI/YOT"
} 



###

DELETE  http://localhost:3000/posts


###

DELETE  http://localhost:3000/posts/67434c5653efbe8185945b36

###


GET http://localhost:3000/comments

###

GET http://localhost:3000/comments?post_id=adawda14123dawdwq21413241


###
  
POST  http://localhost:3000/comments
Content-Type: application/json

{   
"comment": "This is my first comment!",
"commentId": "adawda14123dawdwq21413241",
"owner":"Yotam"
}
###
  
PUT  http://localhost:3000/comments/6772e9c0b8fc22ad6b109449
Content-Type: application/json

{
"comment": "hello!",
"commentId": "44444",
"owner":"Yuri"
} 



###

DELETE  http://localhost:3000/comments/6772e95c587ad7ffc953dfa6

